# This workflow is used to build a lab and push it to AWS S3

name: GitHub to S3
on:
  push:
# mentioning which branch should be used to build the experimnet
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update and install required applications
      run: |
        sudo apt-get update && sudo apt-get install make git awscli -y
        cd civil11-test/src/
        make all
        cd ../
        aws s3 cp ./build/ s3://$S3_BUCKET_NAME/ --recursive --include "*.html" --include "*.js" --include "*.svg"
