# This workflow is used to build a lab and push it to AWS S3
name: GitHub to S3
on:
  push:
# mentioning which branch should be used to run the pipeline
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Updating and installing required applications
    # Followig will update the packages and installs awscli package
      run: sudo apt-get update && sudo apt-get install awscli -y
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: AWS Actions
    # Following will remove contents from backup bucket then move contents of prod bucket to backup and copy new sources to prod bucket
      run: |
           ls 
           aws s3 cp ./civil11-test/ s3://infra-test-main/civil11-test/ --recursive --include "*.html" --include "*.js" --include "*.svg"
